# Generated by Django 5.2 on 2025-04-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(unique=True)),
                ('task_name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
