# Generated by Django 5.2 on 2025-04-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0002_alter_tasks_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='user_name',
        ),
    ]
