# Generated by Django 5.2 on 2025-04-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0003_remove_tasks_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_name',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
