# Generated by Django 5.2 on 2025-04-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0005_alter_tasks_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='completed',
        ),
        migrations.AddField(
            model_name='tasks',
            name='completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(default='Add Description', max_length=200),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_name',
            field=models.TextField(max_length=50),
        ),
    ]
